from typing import Dict, Any


def build_empty_draft_template(draft_id: str,
	video_track_id: str,
	text_track_id: str,
	audio_track_id: str) -> Dict[str, Any]:
	return {
		"id": draft_id,
		"duration": 0,
		"fps": 30.0,
		"canvas_config": {"height": 1920, "width": 1080, "ratio": "original"},
		"color_space": 0,
		"config": {
			"adjust_max_index": 1,
			"attachment_info": [],
			"combination_max_index": 1,
			"export_range": None,
			"extract_audio_last_index": 1,
			"lyrics_recognition_id": "",
			"lyrics_sync": True,
			"lyrics_taskinfo": [],
			"maintrack_adsorb": True,
			"material_save_mode": 0,
			"multi_language_current": "none",
			"multi_language_list": [],
			"multi_language_main": "none",
			"multi_language_mode": "none",
			"original_sound_last_index": 1,
			"record_audio_last_index": 1,
			"sticker_max_index": 1,
			"subtitle_keywords_config": None,
			"subtitle_recognition_id": "",
			"subtitle_sync": True,
			"subtitle_taskinfo": [],
			"system_font_list": [],
			"video_mute": True,
			"zoom_info_params": None,
		},
		"cover": None,
		"create_time": 0,
		"extra_info": None,
		"free_render_index_mode_on": False,
		"group_container": None,
		"keyframe_graph_list": [],
		"keyframes": {k: [] for k in ["adjusts", "audios", "effects", "filters", "handwrites", "stickers", "texts", "videos"]},
		"last_modified_platform": {"app_id": 3704, "app_source": "lv", "app_version": "5.9.0", "device_id": "", "hard_disk_id": "", "mac_address": "", "os": "windows", "os_version": "10.0.20348"},
		"materials": {
			"ai_translates": [], "audio_balances": [], "audio_effects": [], "audio_fades": [], "audio_track_indexes": [],
			"audios": [], "beats": [], "canvases": [], "chromas": [], "color_curves": [], "digital_humans": [],
			"drafts": [], "effects": [], "flowers": [], "green_screens": [], "handwrites": [], "hsl": [], "images": [],
			"log_color_wheels": [], "loudnesses": [], "manual_deformations": [], "masks": [], "material_animations": [],
			"material_colors": [], "multi_language_refs": [], "placeholders": [], "plugin_effects": [],
			"primary_color_wheels": [], "realtime_denoises": [], "shapes": [], "smart_crops": [], "smart_relights": [],
			"sound_channel_mappings": [], "speeds": [], "stickers": [], "tail_leaders": [], "text_templates": [],
			"texts": [], "time_marks": [], "transitions": [], "video_effects": [], "video_trackings": [], "videos": [],
			"vocal_beautifys": [], "vocal_separations": []
		},
		"mutable_config": None,
		"name": "",
		"new_version": "110.0.0",
		"platform": {"app_id": 3704, "app_source": "lv", "app_version": "5.9.0", "device_id": "", "hard_disk_id": "", "mac_address": "", "os": "windows", "os_version": "10.0.20348"},
		"relationships": [],
		"render_index_track_mode_on": True,
		"retouch_cover": None,
		"source": "default",
		"static_cover_image_path": "",
		"time_marks": None,
		"tracks": [
			{"id": video_track_id, "type": "video", "name": "", "is_default_name": True, "flag": 0, "attribute": 1, "track_render_index": 0, "segments": []},
			{"id": text_track_id,  "type": "text",  "name": "", "is_default_name": True, "flag": 0, "attribute": 0, "track_render_index": 1, "segments": []},
			{"id": audio_track_id, "type": "audio", "name": "", "is_default_name": True, "flag": 0, "attribute": 0, "track_render_index": 0, "segments": []}
		],
		"update_time": 0,
		"version": 360000,
	} 